---
season_weeks:               14
sports:
    nfl:
        week_start_day:     thursday # day absolutely MUST be a day of the week, unabbreviated

league:
    capacity:               [ 12, 14, 16 ]
    password_min_length:    6
    password_max_length:    32
