---
user:
    expiry_month:           June
    expiry_day:             1

team_pay_day:               tuesday
player_pay_day:             wednesday
week_start_day:             thursday
league:
    capacity:               12 # NOTE: changing this may require a new scheduling plan
    password_min_length:    6
    password_max_length:    32

season_weeks:               11
playoff_weeks:              3

bench_score_divisor:        3

# TODO: figure out the best way to pull these out into the localization file where it belongs
datetime_format:
    date_full:              '%B %e, %Y'
